// Mocks generated by Mockito 5.0.10 from annotations
// in testing_flutter/test/blocs/product_catalog_bloc_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:testing_flutter/models/product_model.dart' as _i4;
import 'package:testing_flutter/repositories/product_repository.dart' as _i2;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: comment_references
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [ProductRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductRepository extends _i1.Mock implements _i2.ProductRepository {
  MockProductRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.ProductModel>> products() =>
      (super.noSuchMethod(Invocation.method(#products, []),
              returnValue:
                  Future<List<_i4.ProductModel>>.value(<_i4.ProductModel>[]))
          as _i3.Future<List<_i4.ProductModel>>);
}
